// app/lib/interview/contract.js
// The jq-interview/1 contract shared with interview-copilot. See CONTRACT.md at the repo root.
const fs = require('fs');
const os = require('os');
const path = require('path');

const CONTRACT = 'jq-interview/1';
const CONTRACT_MAJOR = 1;
const MARKER_MD = '<!-- generated by job-quest (jq-interview/1); edits are overwritten -->';
const GENERATED_BY = 'job-quest';
const ROUNDS = ['coding', 'system', 'behavioral', 'recruiter', 'screen'];
const INTERVIEW_REPO = 'https://github.com/SideQuest-Collective/interview-copilot';
const PLACEHOLDER = '_(filled in by the /interview skill on stop)_';
const FOLDER_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/;

class ContractError extends Error { constructor(m) { super(m); this.code = 'CONTRACT'; } }
class InputError extends Error { constructor(m) { super(m); this.code = 'INPUT'; } }
class NotFoundError extends Error { constructor(m) { super(m); this.code = 'NOT_FOUND'; } }

function contractMajor(value) {
  const m = /^jq-interview\/(\d+)(?:\.\d+)*$/.exec(String(value == null ? '' : value).trim());
  return m ? Number(m[1]) : null;
}

function assertContract(value, where) {
  if (contractMajor(value) !== CONTRACT_MAJOR) {
    throw new ContractError(`contract mismatch: ${where} uses ${value || 'no contract'}; Job Quest supports ${CONTRACT}`);
  }
}

function assertFolderName(name) {
  const s = String(name == null ? '' : name);
  if (!FOLDER_RE.test(s) || s.includes('..')) throw new InputError(`invalid session folder name: ${s}`);
  return s;
}

function expandHome(p) { return String(p).replace(/^~(?=$|\/)/, os.homedir()); }

function interviewHome(env = process.env) {
  return path.resolve(expandHome(env.INTERVIEW_HOME || path.join(os.homedir(), '.interview')));
}

function interviewInstalled(home) {
  return fs.existsSync(path.join(home, 'app', 'capture.py'));
}

function jobQuestHome(env = process.env) {
  return path.resolve(expandHome(env.JOB_QUEST_HOME || path.join(os.homedir(), '.job-quest')));
}

function dataDirFromEnv(env = process.env) {
  if (env.DATA_DIR) return path.resolve(expandHome(env.DATA_DIR));
  return path.join(jobQuestHome(env), 'data');
}

module.exports = {
  CONTRACT, CONTRACT_MAJOR, MARKER_MD, GENERATED_BY, ROUNDS, INTERVIEW_REPO, PLACEHOLDER,
  ContractError, InputError, NotFoundError,
  contractMajor, assertContract, assertFolderName,
  interviewHome, interviewInstalled, jobQuestHome, dataDirFromEnv,
};
